// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInDca3qJFWTtQhVG7Q7hAFlA0a8E0tgE',
    appId: '1:796278474377:android:0dc9e205a68e61e1912858',
    messagingSenderId: '796278474377',
    projectId: 'todolist-cae6a',
    databaseURL: 'https://todolist-cae6a-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-cae6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfzp7t9ZXde-LvrRAufP_M3XCCMEuyMsw',
    appId: '1:796278474377:ios:e6beddf2412c5f77912858',
    messagingSenderId: '796278474377',
    projectId: 'todolist-cae6a',
    databaseURL: 'https://todolist-cae6a-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-cae6a.appspot.com',
    iosClientId: '796278474377-4lvriqgu1ljl7rh6fgc3jj6pm859co4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.todlist',
  );
}
